// <auto-generated />
namespace VidlyMvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alterAddDobToCustomers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alterAddDobToCustomers));
        
        string IMigrationMetadata.Id
        {
            get { return "201705070632107_alterAddDobToCustomers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
